#!/usr/bin/env python3
import os
import subprocess
from datetime import datetime, timedelta
import sys

# Submits tournament jobs every day for the next 30 days

cmd = sys.argv[1]
count = sys.argv[2]

directory = os.path.dirname(__file__)

today = datetime.today()
first_day = today if today.hour < 18 else today + timedelta(days=1)

next_run = first_day.replace(hour=18, minute=0, second=0, microsecond=0)

for i in range(int(count)):
    date_str = datetime.strftime(next_run, "%Y-%m-%dT%H:%M:%S")
    print("Submitting tournament {} at {}...".format(i + 1, date_str))
    subprocess.run([os.path.join(directory, "tournament"), "{} --begin {}".format(cmd, date_str)])
    next_run += timedelta(days=1)
