#!/usr/bin/env bash

CMD=$1
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

$CMD -J lb_shuffle --ntasks=1 --mem-per-cpu=16000 --time=24:00:00 -C nvd $DIR/../on_node/shuffle_db