#!/usr/bin/env bash

CMD=$1
ARGS="${@:2}"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

$CMD -J lb_training --ntasks=1 --mem-per-cpu=16000 -C nvd --time=24:00:00 $DIR/../on_node/training ${ARGS}